### ISSUE TITLE
1.4.7 Backport

### ISSUE THREAD

**Issue by Traxis** [Myrathi/ObsidiPlatesEx#1]
Would you consider backporting ObisidiPlates updates to 1.4.7? If it isn't too much work, of course.

**Comment by Myrathi** [comment]
Unfortunately, there _would_ be a substantial amount of effort required, as there was a massive refactoring of my build scripts, whole new classes for the extra plates and a new custom renderer just to handle the shrouded ones. If I had done things in a different order, the backport _may_ have been feasible but, as it stands, it'd be extremely tedious and I've already cleared up my 1.4.7 folders.

I appreciate the request, though, and I'm sorry to disappoint. :(
