### ISSUE TITLE
Cosmetic - Obsidian plates pick up incorrect tetures

### ISSUE THREAD

**Issue by dashkal16** [Myrathi/ObsidiPlatesEx#2]
My obsidian plates are picking up incorrect textures.  My silent one got Natura's berry bush, and the normal "pressure plate" got mossy cobblestone.

http://i.imgur.com/TMAkoO7.png

obsidiplates-1.5.1-universal-1.3.2.11
Forge 661
Tested with and without OptiFine

Full mod list:
ImmibisMicroblocksInstallCheck(Immibis's Microblocks (Check for incorrect installation):54.0.6): immibis-microblocks-54.0.6.jar ()
BetterStorage(BetterStorage:0.5.0.3): [1.5.1]BetterStorage_0.5.0.3.zip ()
mod_ReiMinimap(mod_ReiMinimap:Not available): [1.5.1]ReiMinimap_v3.3_04.zip ()
ArsMagica(Ars Magica:5.50.007): ArsMagica_5.50.007.zip ()
BiblioCraft(BiblioCraft:1.1.6): BiblioCraft[v1.1.6].zip ()
ChickenChunks(ChickenChunks:1.3.2.4): ChickenChunks 1.3.2.4.jar (required-after:Forge@[6.4.1.413,))
enhancedportals(Enhanced Portals:2.1.2): enhanced-portals_2.1.2.jar ()
ExtrabiomesXL(ExtrabiomesXL:3.13.0): ExtrabiomesXL-universal-1.5.1-3.13.0.jar ()
ImmibisCore(Immibis Core:54.0.1): immibis-core-54.0.1.jar ()
inventorytweaks(Inventory Tweaks:1.53): InventoryTweaks-1.53.jar (required-after:FML@[5.0.0,);required-after:Forge@[7.7.0,))
IronChest(Iron Chest:5.2.1.284): ironchest-universal-1.5-5.2.1.284.zip (required-after:Forge@[7.0,);required-after:FML@[5.0.5,))
Natura(Natura:1.5.1_2.0.14): Natura_1.5.1_2.0.14.jar ()
ObsidiPlates(Obsidian Pressure Plates:1.3.2): obsidiplates-1.5.1-universal-1.3.2.11.jar ()
Pouches(Pouches:0.8.2): Pouches_1.5.1-0.8.2.zip (required-after:Forge@[7.7.1,))
PrimitiveMobs(PrimitiveMobs:1.4): PrimitiveMobsv1.3.5MC1.5.1.zip ()
TConstruct(Tinkers' Construct:1.5.1_1.3dev.12): TConstruct_1.5.1_1.3dev.12.jar (required-after:Forge@[7.7.1.659,))
Thaumcraft(Thaumcraft:3.0.4a): Thaumcraft3.0.4a.zip (required-after:Forge@[7.7.1.661,);after:BuildCraft|Core;after:BuildCraft|Energy;after:Forestry;after:IC2)
TwilightForest(The Twilight Forest:1.17.1): twilightforest-1.17.1.zip ()
MSC(Mob Spawn Controls:1.5.1.0): Forge_MobSpawnControlsv1.5.1.0.zip (after:*)

**Comment by Myrathi** [comment]
Thanks for the report. This is really, really odd, though, since I pull the `Icon` directly from the block the plate is made from (in this case, obsidian). Even more odd, since the mossy cobble looks fine and the woollen sides, too. O_o
1. Did you get this after activating/switching a texture pack?
2. Is there anything in your `ForgeModLoader-client-0.log` files about any of those mods replacing the obsidian block?

**Comment by dashkal16** [comment]
No texture packs involved at all.
And I'm afraid there's no mention of the obsidian block.  Obsidian in my logs refers to your mod, and the liquid obsidian from Tinker's Construct.

**Comment by dashkal16** [comment]
Isolated it to a cross-mod interaction with Enhanced Portals
http://www.minecraftforum.net/topic/1301217-1511st-apr-enhanced-portals/

**Comment by Myrathi** [comment]
Just uploaded a new 1.5.2 version. Does this still happen with it? (no idea if there's an enhanced portals for 1.5.2)

**Comment by maxell45146** [comment]
MC 1.5.2 Obsidian Plates 1.5.0.13 Enchanced Portals 2.1.2 

Its acting the same as it did in 1.5.1, I'm assuming EP changes obsidian and OP looks at it thinking its the original. Could OP be made to just have a obsidian texture?

**Comment by Myrathi** [comment]
That would mean it wouldn't pick up the texture of peoples' texture pack overrides. Enhanced Portals needs to return a valid `Icon` for the sided texture method or fix their damn code. :\

**Comment by ShadedDimension** [comment]
I now use reflection to change the obsidian block - I guess Block.obsidian was returning invalid icons even though that's what I was using to get my icons. Seems to be working fine now.

https://github.com/ShadedDimension/enhanced-portals/commit/3d192ab2c5f8d07398323d6aca495dca1661fb48

**Comment by Myrathi** [comment]
From skimming your pre-fix code, it looks like the timings ran such that you were replacing the block with your own _after_ ObP had grabbed its reference, invalidating any Icon references from that point onwards. Without your moving to reflection (and proper use of the `Block.obsidian` field ^_^), I'd never have been able to pull the right textures without hardcoding the vanilla resource path.

IOW: well fixed and thanks for posting. :)
