### ISSUE TITLE
Crash with 1.5.2

### ISSUE THREAD

**Issue by DocHuzz** [Myrathi/ObsidiPlatesEx#3]
After extensive testing, I have discovered that Obsidiplates is causing this crash: http://pastebin.com/ibeSZ9Vw (FMLlog)/http://pastebin.com/mB6GC84B (Clientlog)

I know both say NEI and Railcraft, but this was at the time I was assuming multiple conflicts with NEI.  MultiMC didn't remove Obsidiplates, which was causing the problems.

Replication is as simple as entering the creative menu or by using NEI and tabbing over to the Obsidiplates.

**Comment by Myrathi** [comment]
Already fixed. Check the FTB forum post for the new version. :)
